#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication blockMesh
runApplication decomposePar -force
runParallel $application
runApplication reconstructPar

#------------------------------------------------------------------------------
