#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication topoSet -dict topoSetDict.1
runApplication refineMesh -overwrite -dict refineMeshDict.1
mv log.topoSet log.toposet1
mv log.refineMesh log.refineMesh1
runApplication topoSet -dict topoSetDict.2
runApplication refineMesh -overwrite -dict refineMeshDict.2
mv log.topoSet log.toposet2
mv log.refineMesh log.refineMesh2
runApplication topoSet -dict topoSetDict.3
runApplication refineMesh -overwrite -dict refineMeshDict.3
mv log.topoSet log.toposet3
mv log.refineMesh log.refineMesh3
#------------------------------------------------------------------------------
